# Generated by Django 5.1.4 on 2024-12-11 17:42

import django.db.models.deletion
import modelcluster.fields
import wagtail.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wagtailcore", "0094_alter_page_locale"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AccessProtocol",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AssetType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Discipline",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Domain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MetadataStandard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Region",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Subregion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "region",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subregions",
                        to="ropon_data.region",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ObservingNetwork",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "live",
                    models.BooleanField(
                        default=True, editable=False, verbose_name="live"
                    ),
                ),
                (
                    "has_unpublished_changes",
                    models.BooleanField(
                        default=False,
                        editable=False,
                        verbose_name="has unpublished changes",
                    ),
                ),
                (
                    "first_published_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        null=True,
                        verbose_name="first published at",
                    ),
                ),
                (
                    "last_published_at",
                    models.DateTimeField(
                        editable=False, null=True, verbose_name="last published at"
                    ),
                ),
                (
                    "go_live_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="go live date/time"
                    ),
                ),
                (
                    "expire_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="expiry date/time"
                    ),
                ),
                (
                    "expired",
                    models.BooleanField(
                        default=False, editable=False, verbose_name="expired"
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("network_abbreviation", models.CharField(max_length=255)),
                ("network_description", models.TextField()),
                ("network_website", models.URLField()),
                (
                    "network_logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="network_logos/"
                    ),
                ),
                ("network_ropon_id", models.CharField(max_length=255, unique=True)),
                (
                    "organization",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("spatial_extent", models.TextField(blank=True, null=True)),
                ("year_started", models.PositiveIntegerField(blank=True, null=True)),
                ("contact", models.CharField(max_length=255)),
                ("data_repository", models.URLField(blank=True, null=True)),
                (
                    "asset_metadata_catalog",
                    models.CharField(
                        choices=[
                            ("yes", "Yes"),
                            ("no", "No"),
                            ("under_development", "Under Development"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "metadata_access",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("yes", "Yes"),
                            ("no", "No"),
                            ("under_development", "Under Development"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "machine_readable_access",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("yes", "Yes"),
                            ("no", "No"),
                            ("under_development", "Under Development"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("metadata_catalog_links", models.URLField(blank=True, null=True)),
                ("date_last_modified", models.DateField(auto_now=True)),
                (
                    "access_protocols",
                    modelcluster.fields.ParentalManyToManyField(
                        blank=True, to="ropon_data.accessprotocol"
                    ),
                ),
                (
                    "asset_types",
                    modelcluster.fields.ParentalManyToManyField(
                        blank=True, to="ropon_data.assettype"
                    ),
                ),
                (
                    "disciplines",
                    modelcluster.fields.ParentalManyToManyField(
                        blank=True, to="ropon_data.discipline"
                    ),
                ),
                (
                    "domains",
                    modelcluster.fields.ParentalManyToManyField(
                        blank=True, to="ropon_data.domain"
                    ),
                ),
                (
                    "last_modified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="modified_observing_networks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "latest_revision",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailcore.revision",
                        verbose_name="latest revision",
                    ),
                ),
                (
                    "live_revision",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailcore.revision",
                        verbose_name="live revision",
                    ),
                ),
                (
                    "metadata_standards",
                    modelcluster.fields.ParentalManyToManyField(
                        blank=True, to="ropon_data.metadatastandard"
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="observing_networks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "regions",
                    modelcluster.fields.ParentalManyToManyField(
                        blank=True, to="ropon_data.region"
                    ),
                ),
                (
                    "subregions",
                    modelcluster.fields.ParentalManyToManyField(
                        blank=True, to="ropon_data.subregion"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(wagtail.models.WorkflowMixin, models.Model),
        ),
    ]
