#!/bin/sh

# Serve Django project at 0:8000
# Usage: run

cd
[ -d .local ] || pip install --user -r requirements.txt
#[ -d static ] || ./manage.py collectstatic --noinput
./manage.py runserver 0.0.0.0:8000
