
services:
  wagtail:
    image: arcticportal.azurecr.io/ropon/wagtail
    command: ./docker-entrypoint.sh
    env_file:
      - .env.prd

  db:
    image: postgis/postgis:17-3.5
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - .env.prd

volumes:
  postgres-data: