# Generated by Django 5.1.5 on 2025-01-30 14:46

import django.db.models.deletion
import modelcluster.fields
import ropon_data.validators
import uuid
import wagtail.fields
import wagtail.search.index
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wagtailcore", "0094_alter_page_locale"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccessProtocol",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description of the access protocol, including examples of the types of access protocols that fall under this category.",
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "source_url",
                    models.URLField(
                        blank=True,
                        help_text="URL to the official documentation or website for the access protocol.",
                        null=True,
                        verbose_name="Source URL",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AssetType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description of the asset type, including examples of the types of assets that fall under this category.",
                        null=True,
                        verbose_name="Description",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Discipline",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Domain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MetadataStandard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description of the metadata standard, including examples of the types of metadata that fall under this category.",
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "source_url",
                    models.URLField(
                        blank=True,
                        help_text="URL to the official documentation or website for the metadata standard.",
                        null=True,
                        verbose_name="Source URL",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ObservingNetworkIndexPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("intro", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Observing Networks Page",
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Organization name"),
                ),
            ],
            options={
                "verbose_name": "Organization",
                "verbose_name_plural": "Organizations",
            },
            bases=(wagtail.search.index.Indexed, models.Model),
        ),
        migrations.CreateModel(
            name="Region",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Subregion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ObservingNetworkPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="The full name of the observing network e.g. Svalbard Integrated Arctic Earth Observing System",
                        max_length=255,
                        verbose_name="Network Name",
                    ),
                ),
                (
                    "is_owner_authorized",
                    models.BooleanField(default=False, editable=False),
                ),
                (
                    "abbreviation",
                    models.CharField(
                        help_text="Acronym or short name of the observing network. e.g. SIOS",
                        max_length=255,
                        verbose_name="Network Abbreviation",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Short summary of the observing network, including geographic or thematic scope.",
                        verbose_name="Network Description",
                    ),
                ),
                (
                    "website_url",
                    models.URLField(
                        help_text="URL to the observing network website",
                        verbose_name="Network Website",
                    ),
                ),
                (
                    "logo_url",
                    models.URLField(
                        help_text="URL to the observing network logo",
                        verbose_name="Network Logo",
                    ),
                ),
                (
                    "ropon_id",
                    models.CharField(
                        default=uuid.uuid4,
                        help_text="Unique identifier for the observing network in the ROPO database.",
                        max_length=255,
                        unique=True,
                        verbose_name="ROPON ID",
                    ),
                ),
                (
                    "geometry_field",
                    wagtail.fields.StreamField(
                        [("bounding_box", 4)],
                        block_lookup={
                            0: (
                                "wagtail.blocks.FloatBlock",
                                (),
                                {
                                    "label": "Latitude",
                                    "validators": [
                                        ropon_data.validators.validate_latitude
                                    ],
                                },
                            ),
                            1: (
                                "wagtail.blocks.FloatBlock",
                                (),
                                {
                                    "label": "Longitude",
                                    "validators": [
                                        ropon_data.validators.validate_longitude
                                    ],
                                },
                            ),
                            2: (
                                "wagtail.blocks.StructBlock",
                                [[("latitude", 0), ("longitude", 1)]],
                                {"label": "SouthWest Corner"},
                            ),
                            3: (
                                "wagtail.blocks.StructBlock",
                                [[("latitude", 0), ("longitude", 1)]],
                                {"label": "NorthEast Corner"},
                            ),
                            4: (
                                "wagtail.blocks.StructBlock",
                                [[("southwest", 2), ("northeast", 3)]],
                                {"label": "Bounding Box"},
                            ),
                        },
                        help_text="Spatial coverage of the network as delineated by one or more bounding boxes. Each box is defined as a pair of latitude and longitude coordinates for the southwest and northeast corners.",
                        verbose_name="Spatial Extent",
                    ),
                ),
                (
                    "start_year",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="The year that observations within the network began.",
                        null=True,
                        validators=[ropon_data.validators.validate_start_year],
                        verbose_name="Year Started",
                    ),
                ),
                (
                    "contact",
                    models.CharField(
                        help_text="Email address or URL for contacting the observing network.",
                        max_length=255,
                        validators=[ropon_data.validators.validate_email_or_url],
                        verbose_name="Contact",
                    ),
                ),
                (
                    "data_repository_url",
                    wagtail.fields.StreamField(
                        [("url", 0)],
                        blank=True,
                        block_lookup={
                            0: (
                                "wagtail.blocks.URLBlock",
                                (),
                                {"label": "Data Repository URL"},
                            )
                        },
                        help_text="One or more links to data repositories hosting scientific data from the network (such as the Polar Data Catalogue, NSF Arctic Data Center, or PANGAEA).  (This field pertains to scientific datasets, not observing assets).",
                        null=True,
                        verbose_name="Data Repository",
                    ),
                ),
                (
                    "has_catalog",
                    models.CharField(
                        choices=[
                            ("yes", "Yes"),
                            ("no", "No"),
                            ("under_development", "Under Development"),
                        ],
                        help_text="Does the network has a catalog, spreadsheet, list, or other means of tracking details about individual observing assets such as observing sites, mobile platforms, research projects, field campaigns, cruises, programs, etc.?  (This field pertains to observing assets, not scientific datasets). ",
                        max_length=20,
                        verbose_name="Asset Metadata Catalog",
                    ),
                ),
                (
                    "metadata_access",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("yes", "Yes"),
                            ("no", "No"),
                            ("under_development", "Under Development"),
                        ],
                        help_text="Is the network's asset-level catalog, spreadsheet, list, or other documentation enabled online for public viewing, download, or other access?",
                        max_length=20,
                        null=True,
                        verbose_name="Metadata Access",
                    ),
                ),
                (
                    "machine_readable",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("yes", "Yes"),
                            ("no", "No"),
                            ("under_development", "Under Development"),
                        ],
                        help_text="Is the network's asset-level metadata catalog enabled for access with an API or endpoint URL for automated harvesting of asset-level metadata records?",
                        max_length=20,
                        null=True,
                        verbose_name="Machine Readable Access",
                    ),
                ),
                (
                    "metadata_catalog_url",
                    wagtail.fields.StreamField(
                        [("url", 0)],
                        blank=True,
                        block_lookup={
                            0: (
                                "wagtail.blocks.URLBlock",
                                (),
                                {"label": "Metadata Catalog URL"},
                            )
                        },
                        help_text="Link to one or more webpages presenting a network's catalog, spreadsheet, list, or other documentation about observing assets.",
                        null=True,
                        verbose_name="Metadata Catalog Links",
                    ),
                ),
                (
                    "access_protocols",
                    modelcluster.fields.ParentalManyToManyField(
                        blank=True,
                        help_text="Transfer protocols or web service formats in use for public access to a network's structured information about observing assets (such as file download, custom API, OGC WMS, or OAI-PMH).",
                        to="ropon_data.accessprotocol",
                        verbose_name="Access Protocols",
                    ),
                ),
                (
                    "asset_types",
                    modelcluster.fields.ParentalManyToManyField(
                        help_text="Categorization of discrete infrastructure or coordinated activities for observing such as sites, mobile platforms, projects, campaigns, and initiatives.",
                        to="ropon_data.assettype",
                        verbose_name="Asset Types",
                    ),
                ),
                (
                    "disciplines",
                    modelcluster.fields.ParentalManyToManyField(
                        help_text="Branch of scientific knowledge or thematic focus for the observing network.",
                        to="ropon_data.discipline",
                        verbose_name="Disciplines",
                    ),
                ),
                (
                    "domains",
                    modelcluster.fields.ParentalManyToManyField(
                        help_text="Scope of observations across Atmosphere, Land, and/or Ocean.",
                        to="ropon_data.domain",
                        verbose_name="Domains",
                    ),
                ),
                (
                    "metadata_standards",
                    modelcluster.fields.ParentalManyToManyField(
                        blank=True,
                        help_text="Metadata standards, or a custom schema, in use for public access to a network's structured information about observing assets (such as ISO 19115, INSPIRE EF, WMO WIGOS, etc.).",
                        to="ropon_data.metadatastandard",
                        verbose_name="Metadata Standards",
                    ),
                ),
                (
                    "regions",
                    modelcluster.fields.ParentalManyToManyField(
                        help_text="Spatial coverage of the network as described by one or more broad geographical areas, such as Arctic, Antarctica, Southern Ocean, etc.",
                        to="ropon_data.region",
                        verbose_name="Regions",
                    ),
                ),
                (
                    "subregions",
                    modelcluster.fields.ParentalManyToManyField(
                        help_text="Spatial coverage of the network as described by smaller geographic areas, such as Alaska, Iceland, Beaufort Sea, Russian Subarctic, West Antarctica, Ross Sea, etc.",
                        to="ropon_data.subregion",
                        verbose_name="Subregions",
                    ),
                ),
            ],
            options={
                "verbose_name": "Observing Network",
                "permissions": [
                    (
                        "publish_observingnetworkpage",
                        "Can publish observing network page",
                    )
                ],
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="ObservingNetworkOrganization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "observingnetwork",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="network_organizations",
                        to="ropon_data.observingnetworkpage",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="organizations_networks",
                        to="ropon_data.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Observing Network Organization",
                "verbose_name_plural": "Observing Network Organizations",
            },
        ),
    ]
