# Generated by Django 5.1.4 on 2025-01-20 23:55

import ropon_data.validators
import uuid
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ropon_data", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="observingnetworkpage",
            name="geometry_field",
            field=wagtail.fields.StreamField(
                [("bounding_box", 4)],
                block_lookup={
                    0: (
                        "wagtail.blocks.FloatBlock",
                        (),
                        {
                            "label": "Latitude",
                            "validators": [ropon_data.validators.validate_latitude],
                        },
                    ),
                    1: (
                        "wagtail.blocks.FloatBlock",
                        (),
                        {
                            "label": "Longitude",
                            "validators": [ropon_data.validators.validate_longitude],
                        },
                    ),
                    2: (
                        "wagtail.blocks.StructBlock",
                        [[("latitude", 0), ("longitude", 1)]],
                        {"label": "SouthWest Corner"},
                    ),
                    3: (
                        "wagtail.blocks.StructBlock",
                        [[("latitude", 0), ("longitude", 1)]],
                        {"label": "NorthEast Corner"},
                    ),
                    4: (
                        "wagtail.blocks.StructBlock",
                        [[("southwest", 2), ("northeast", 3)]],
                        {"label": "Bounding Box"},
                    ),
                },
                help_text="Spatial coverage of the network as delineated by one or more bounding boxes. Each box is defined as a pair of latitude and longitude coordinates for the southwest and northeast corners.",
                verbose_name="Spatial Extent",
            ),
        ),
        migrations.AlterField(
            model_name="observingnetworkpage",
            name="metadata_catalog_url",
            field=wagtail.fields.StreamField(
                [("url", 0)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {"label": "Metadata Catalog URL"},
                    )
                },
                help_text="Link to one or more webpages presenting a network's catalog, spreadsheet, list, or other documentation about observing assets.",
                null=True,
                verbose_name="Metadata Catalog Links",
            ),
        ),
        migrations.AlterField(
            model_name="observingnetworkpage",
            name="ropon_id",
            field=models.CharField(
                default=uuid.uuid4,
                help_text="Unique identifier for the observing network in the ROPO database.",
                max_length=255,
                unique=True,
                verbose_name="ROPON ID",
            ),
        ),
    ]
