# Generated by Django 5.1.9 on 2025-06-02 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ropon_data", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="observingnetworkpage",
            name="logo_url",
            field=models.URLField(
                blank=True,
                help_text="URL to the observing network logo.(must be .png, .jpg, .jpeg or .svg format)",
                null=True,
                verbose_name="Network Logo",
            ),
        ),
        migrations.AlterField(
            model_name="observingnetworkpage",
            name="machine_readable",
            field=models.CharField(
                blank=True,
                choices=[
                    ("yes", "Yes"),
                    ("no", "No"),
                    ("under_development", "Under Development"),
                ],
                help_text="Is the network's asset-level metadata catalog enabled for access with an API or endpoint URL for automated harvesting of asset-level metadata records? If partially enabled, select Yes.",
                max_length=20,
                null=True,
                verbose_name="Machine Readable Access",
            ),
        ),
        migrations.AlterField(
            model_name="observingnetworkpage",
            name="metadata_access",
            field=models.CharField(
                blank=True,
                choices=[
                    ("yes", "Yes"),
                    ("no", "No"),
                    ("under_development", "Under Development"),
                ],
                help_text="Is the network's asset-level catalog, spreadsheet, list, or other documentation enabled online for public viewing, download, or other access? If partially enabled, select Yes.",
                max_length=20,
                null=True,
                verbose_name="Metadata Access",
            ),
        ),
    ]
