# Generated by Django 5.1.6 on 2025-03-04 23:58

import django.db.models.deletion
import ropon_data.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ropon_data", "0001_initial"),
        ("wagtailimages", "0026_delete_uploadedimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="observingnetworkpage",
            name="logo_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
            ),
        ),
        migrations.AlterField(
            model_name="observingnetworkpage",
            name="logo_url",
            field=models.URLField(
                help_text="URL to the observing network logo.(must be .png, .jpg, .jpeg or .svg format)",
                validators=[ropon_data.validators.validate_image_url],
                verbose_name="Network Logo",
            ),
        ),
    ]
