# Generated by Django 5.1.4 on 2025-01-05 23:11

import ropon_data.validators
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ropon_data", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="observingnetworkpage",
            name="geometry_field",
            field=wagtail.fields.StreamField(
                [("polygon", 0), ("bounding_box", 5)],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {}),
                    1: (
                        "wagtail.blocks.FloatBlock",
                        (),
                        {
                            "help_text": "Northern latitude (-90 to 90)",
                            "validators": [ropon_data.validators.validate_latitude],
                        },
                    ),
                    2: (
                        "wagtail.blocks.FloatBlock",
                        (),
                        {
                            "help_text": "Southern latitude (-90 to 90)",
                            "validators": [ropon_data.validators.validate_latitude],
                        },
                    ),
                    3: (
                        "wagtail.blocks.FloatBlock",
                        (),
                        {
                            "help_text": "Eastern longitude (-180 to 180)",
                            "validators": [ropon_data.validators.validate_longitude],
                        },
                    ),
                    4: (
                        "wagtail.blocks.FloatBlock",
                        (),
                        {
                            "help_text": "Western longitude (-180 to 180)",
                            "validators": [ropon_data.validators.validate_longitude],
                        },
                    ),
                    5: (
                        "wagtail.blocks.StructBlock",
                        [[("north", 1), ("south", 2), ("east", 3), ("west", 4)]],
                        {},
                    ),
                },
                help_text='Spatial coverage of the network as delineated by one or more polygons, each as a series of four or more points in latitude and longitude (decimal degrees), where the first and final points are identical (e.g., "polygon": "67.6199 -42.3773 67.6199 17.1685 57.7191 17.1685 57.7191 -42.3773 67.6199 -42.3773").',
                null=True,
                verbose_name="Spatial Extent",
            ),
        ),
        migrations.AlterField(
            model_name="observingnetworkpage",
            name="start_year",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="The year that observations within the network began.",
                null=True,
                validators=[ropon_data.validators.validate_start_year],
                verbose_name="Year Started",
            ),
        ),
    ]
