# Generated by Django 5.1.5 on 2025-01-30 00:12

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ropon_data", "0002_organization"),
    ]

    operations = [
        migrations.CreateModel(
            name="ObservingNetworkPageOrganization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "observingnetwork",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="network_organizations",
                        to="ropon_data.observingnetworkpage",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="organizations_networks",
                        to="ropon_data.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Observing Network Organization",
                "verbose_name_plural": "Observing Network Organizations",
            },
        ),
    ]
