# Generated by Django 5.1.4 on 2025-01-21 01:01

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ropon_data", "0002_alter_observingnetworkpage_geometry_field_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="observingnetworkpage",
            name="data_repository_url",
            field=wagtail.fields.StreamField(
                [("url", 0)],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.URLBlock", (), {"label": "Data Repository URL"})
                },
                help_text="One or more links to data repositories hosting scientific data from the network (such as the Polar Data Catalogue, NSF Arctic Data Center, or PANGAEA).  (This field pertains to scientific datasets, not observing assets).",
                null=True,
                verbose_name="Data Repository",
            ),
        ),
    ]
