# Generated by Django 5.1.12 on 2025-09-17 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ropon_data", "0002_alter_observingnetworkpage_logo_url_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="accessprotocol",
            options={"ordering": ["sort_order", "id"]},
        ),
        migrations.AlterModelOptions(
            name="assettype",
            options={"ordering": ["sort_order", "id"]},
        ),
        migrations.AlterModelOptions(
            name="discipline",
            options={"ordering": ["sort_order", "id"]},
        ),
        migrations.AlterModelOptions(
            name="domain",
            options={"ordering": ["sort_order", "id"]},
        ),
        migrations.AlterModelOptions(
            name="metadatastandard",
            options={"ordering": ["sort_order", "id"]},
        ),
        migrations.AlterModelOptions(
            name="region",
            options={"ordering": ["sort_order", "id"]},
        ),
        migrations.AlterModelOptions(
            name="subregion",
            options={"ordering": ["sort_order", "id"]},
        ),
        migrations.AddField(
            model_name="accessprotocol",
            name="sort_order",
            field=models.PositiveIntegerField(
                default=0, help_text="Order for display. Use 0 for default ordering."
            ),
        ),
        migrations.AddField(
            model_name="assettype",
            name="sort_order",
            field=models.PositiveIntegerField(
                default=0, help_text="Order for display. Use 0 for default ordering."
            ),
        ),
        migrations.AddField(
            model_name="discipline",
            name="sort_order",
            field=models.PositiveIntegerField(
                default=0, help_text="Order for display. Use 0 for default ordering."
            ),
        ),
        migrations.AddField(
            model_name="domain",
            name="sort_order",
            field=models.PositiveIntegerField(
                default=0, help_text="Order for display. Use 0 for default ordering."
            ),
        ),
        migrations.AddField(
            model_name="metadatastandard",
            name="sort_order",
            field=models.PositiveIntegerField(
                default=0, help_text="Order for display. Use 0 for default ordering."
            ),
        ),
        migrations.AddField(
            model_name="region",
            name="sort_order",
            field=models.PositiveIntegerField(
                default=0, help_text="Order for display. Use 0 for default ordering."
            ),
        ),
        migrations.AddField(
            model_name="subregion",
            name="sort_order",
            field=models.PositiveIntegerField(
                default=0, help_text="Order for display. Use 0 for default ordering."
            ),
        ),
        migrations.AlterField(
            model_name="observingnetworkpage",
            name="has_catalog",
            field=models.CharField(
                choices=[
                    ("yes", "Yes"),
                    ("no", "No"),
                    ("under_development", "Under Development"),
                ],
                help_text="Does the network have a catalog, spreadsheet, list, or other means of tracking details about individual observing assets such as observing sites, mobile platforms, research projects, field campaigns, cruises, programs, etc.?  (This field pertains to observing assets, not scientific datasets). ",
                max_length=20,
                verbose_name="Asset Metadata Catalog",
            ),
        ),
    ]
