# Generated by Django 5.1.4 on 2025-01-06 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ropon_data", "0002_observingnetworkpage_geometry_field_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="observingnetworkpage",
            old_name="geometry",
            new_name="geometry_string",
        ),
    ]
