# Generated by Django 5.1.12 on 2025-09-20 19:51

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "ropon_data",
            "0003_alter_accessprotocol_options_alter_assettype_options_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="observingnetworkpage",
            name="network_id",
            field=wagtail.fields.StreamField(
                [("network_id", 0)],
                blank=True,
                block_lookup={
                    0: ("ropon_data.blocks.NetworkIdBlock", (), {"label": "Network ID"})
                },
                help_text="An identifier for the network generated by an organization, registry, or catalog. e.g. NOAA EORES ID: 370366",
                null=True,
                verbose_name="Network IDs",
            ),
        ),
    ]
