# Generated by Django 5.1.12 on 2025-10-09 16:12

import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ropon_data", "0005_alter_observingnetworkpage_network_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="observingnetworkpage",
            name="asset_types",
            field=modelcluster.fields.ParentalManyToManyField(
                blank=True,
                help_text="Categorization of discrete infrastructure or coordinated activities for observing such as sites, mobile platforms, projects, campaigns, and initiatives.",
                to="ropon_data.assettype",
                verbose_name="Asset Types",
            ),
        ),
        migrations.AlterField(
            model_name="observingnetworkpage",
            name="has_catalog",
            field=models.CharField(
                blank=True,
                choices=[
                    ("yes", "Yes"),
                    ("no", "No"),
                    ("under_development", "Under Development"),
                ],
                help_text="Does the network have a catalog, spreadsheet, list, or other means of tracking details about individual observing assets such as observing sites, mobile platforms, research projects, field campaigns, cruises, programs, etc.?  (This field pertains to observing assets, not scientific datasets). ",
                max_length=20,
                null=True,
                verbose_name="Asset Metadata Catalog",
            ),
        ),
    ]
