# Generated by Django 5.1.12 on 2025-10-09 16:19

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ropon_data", "0006_alter_observingnetworkpage_asset_types_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="observingnetworkpage",
            name="network_id",
            field=wagtail.fields.StreamField(
                [("network_id", 0)],
                blank=True,
                block_lookup={
                    0: ("ropon_data.blocks.NetworkIdBlock", (), {"label": "Network ID"})
                },
                help_text="An identifier for the network generated by an organization, registry, or catalog (Text or URL). e.g. network identifiers from ROR, DEIMS-SDR, RRID, Zenodo Communities, NOAA EORES, etc.",
                null=True,
                verbose_name="Network IDs",
            ),
        ),
    ]
