# Generated by Django 5.1.13 on 2026-02-04 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ropon_data", "0007_alter_observingnetworkpage_network_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="name",
            field=models.CharField(
                help_text="One or more entities responsible for funding or operation of the observing network. Include acronyms in parentheses. e.g. World Meteorological Organization (WMO)",
                max_length=255,
                verbose_name="Organization name",
            ),
        ),
    ]
