# Generated by Django 5.1.15 on 2026-08-05 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ropon_data", "0008_alter_organization_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="observingnetworkpage",
            name="description",
            field=models.TextField(
                help_text="Short summary of the observing network, including geographic or thematic scope. Enter as a single paragraph.",
                verbose_name="Network Description",
            ),
        ),
    ]
