# Assumes that Nginx is a separate Docker process.
# TODO: Replace "DOMAIN" with the correct name when we have one.

server {
  listen 80;
  server_name DOMAIN www.DOMAIN;
  return 301 https://DOMAIN$request_uri; }

server {
  listen 443 ssl;
  server_name DOMAIN www.DOMAIN;
  include /etc/letsencrypt/options-ssl-nginx.conf;
  ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;
  ssl_certificate /etc/letsencrypt/live/DOMAIN/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/DOMAIN/privkey.pem;

  if ($host = www.DOMAIN) {
    return 301 https://DOMAIN$request_uri; }

  location / {
    proxy_pass http://host.docker.internal:60002;  # internal nginx

    proxy_http_version 1.1;
    proxy_read_timeout 3600s;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection upgrade;

    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Real-IP $remote_addr;
    # Add logging here if needed
  } }
