# Generated by Django 5.1.3 on 2024-12-03 02:16

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ropon_pages", "0002_roponpagelisting"),
    ]

    operations = [
        migrations.AlterField(
            model_name="roponpage",
            name="body",
            field=wagtail.fields.StreamField(
                [("heading", 2), ("paragraph", 3), ("image", 4)],
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {"required": True}),
                    1: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("h1", "H1"),
                                ("h2", "H2"),
                                ("h3", "H3"),
                                ("h4", "H4"),
                            ]
                        },
                    ),
                    2: (
                        "wagtail.blocks.StructBlock",
                        [[("heading_text", 0), ("header_level", 1)]],
                        {},
                    ),
                    3: ("wagtail.blocks.RichTextBlock", (), {}),
                    4: ("ropon_pages.blocks.RoponImageChooserBlock", (), {}),
                },
            ),
        ),
    ]
