"""
Django settings for ropon project.

Generated by 'django-admin startproject' using Django 5.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os
from environs import Env

env = Env()
env.read_env()  


from .utils import ( build_urls_from_hosts,
                     set_os_path
    )

PROJECT_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
BASE_DIR = os.path.dirname(PROJECT_DIR)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/


# Application definition

LOCAL_APPS = [
    "home",
    "base",
    "ropon_auth",
    "ropon_data",
    "ropon_pages",
    "ropon",
    "search",
    "ropon_email", # Add the new email app
]

DJANGO_APPS = [
    "taggit",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    'corsheaders',
    'flags'
]

WAGTAIL_APPS = [
    
    "wagtail.contrib.forms",
    "wagtail.contrib.redirects",
    "wagtail.contrib.settings",
    "wagtail_guide",
    "wagtail.embeds",
    "wagtail.sites",
    # "wagtail.users",
    "ropon.apps.RoponUsersAppConfig",  # Custom Wagtail users app config
    "wagtail.snippets",
    "wagtail.documents",
    "wagtail.images",
    "wagtail.search",
    "wagtail.admin",
    "wagtail",
    "modelcluster",
    'wagtail.api.v2',

    ]

THIRD_PARTY_APPS = [
        # 'cookie_consent'
]

INSTALLED_APPS = DJANGO_APPS + WAGTAIL_APPS + THIRD_PARTY_APPS + LOCAL_APPS 

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "wagtail.contrib.redirects.middleware.RedirectMiddleware",
  
]

ROOT_URLCONF = "ropon.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [
            os.path.join(PROJECT_DIR, "templates"),
        ],
        "APP_DIRS": True,
        "OPTIONS": {
            'debug': True,
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "django.template.context_processors.request",
            ],
        },
    },
]


WSGI_APPLICATION = "ropon.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        'NAME': env.str('POSTGRES_DB', default='postgres'),
        'USER': env.str('POSTGRES_USER', default='postgres'),
        'PASSWORD': env.str('POSTGRES_PASSWORD', default='postgres'), 
        'HOST': env.str('POSTGRES_HOST', default='db'),
        'PORT': env.str('POSTGRES_PORT', default='5432'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATICFILES_FINDERS = [
    "django.contrib.staticfiles.finders.FileSystemFinder",
    "django.contrib.staticfiles.finders.AppDirectoriesFinder",
]

STATICFILES_DIRS = [
    os.path.join(PROJECT_DIR, "static"),
]

STATIC_ROOT = os.path.join(BASE_DIR, "static")
STATIC_URL = "/static/"

# Media files (user-uploaded files)
MEDIA_ROOT = env.str('MEDIA_ROOT', os.path.join(BASE_DIR, "media"))
MEDIA_URL = env.str('MEDIA_URL', "/media/")

r= set_os_path(MEDIA_ROOT)

# Default storage settings, with the staticfiles storage updated.
# See https://docs.djangoproject.com/en/5.1/ref/settings/#std-setting-STORAGES
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    # ManifestStaticFilesStorage is recommended in production, to prevent
    # outdated JavaScript / CSS assets being served from cache
    # (e.g. after a Wagtail upgrade).
    # See https://docs.djangoproject.com/en/5.1/ref/contrib/staticfiles/#manifeststaticfilesstorage
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.ManifestStaticFilesStorage",
    },
}


# Wagtail settings

WAGTAIL_SITE_NAME = env.str('WAGTAIL_SITE_NAME','Registry of Polar Networks')

# disable commenting in page editors
WAGTAILADMIN_COMMENTS_ENABLED = env.bool('WAGTAILADMIN_COMMENTS_ENABLED', False)
# disable password reset for users
WAGTAIL_PASSWORD_RESET_ENABLED = env.bool('WAGTAIL_PASSWORD_RESET_ENABLED', False)

WAGTAIL_ENABLE_WHATS_NEW_BANNER = env.bool('WAGTAIL_ENABLE_WHATS_NEW_BANNER', False)
WAGTAIL_ENABLE_UPDATE_CHECK = env.bool('WAGTAIL_ENABLE_UPDATE_CHECK', False)


# Administrator email for user support (used in login template)
ROPON_ADMIN_EMAIL = env.str('ROPON_ADMIN_EMAIL', 'admin@ropon.org')


# Search
# https://docs.wagtail.org/en/stable/topics/search/backends.html
WAGTAILSEARCH_BACKENDS = {
    "default": {
        "BACKEND": "wagtail.search.backends.database",
    }
}

# Base URL to use when referring to full URLs within the Wagtail admin backend -
# e.g. in notification emails. Don't include '/admin' or a trailing slash
WAGTAILADMIN_BASE_URL = env.str("WAGTAILADMIN_BASE_URL", "http://localhost:8000")

# Frontend URL for linking to static pages on the frontend website
# If FRONTEND_URL is not set or empty in .env, fall back to WAGTAILADMIN_BASE_URL
# This is used to generate URLs for frontend static pages
FRONTEND_URL = env.str("FRONTEND_URL", "").strip() or WAGTAILADMIN_BASE_URL

# Allowed file extensions for documents in the document library.
# This can be omitted to allow all files, but note that this may present a security risk
# if untrusted users are allowed to upload files -
# see https://docs.wagtail.org/en/stable/advanced_topics/deploying.html#user-uploaded-files
WAGTAILDOCS_EXTENSIONS = ['csv', 'docx', 'key', 'odt', 'pdf', 'pptx', 'rtf', 'txt', 'xlsx', 'zip']

# SECURITY WARNING: define the correct hosts in production!


ALLOWED_HOSTS = ['127.0.0.1', 'localhost'] + list(filter(None, env.str('DJANGO_ALLOWED_HOSTS', '').split(',')))


# CSRF


CSRF_TRUSTED_ORIGINS = build_urls_from_hosts( 
    env('CSRF_TRUSTED_ORIGINS',None),
        ['http://localhost:8000'] 
        )
                
# CORS
CORS_ALLOWED_ORIGINS = build_urls_from_hosts(
    env('CORS_ALLOWED_ORIGINS',
               None),
               ['http://localhost:8000'] )


DEBUG = True

# Set custom user model
AUTH_USER_MODEL = 'ropon_auth.RoponUser'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field
# commented out to avoid migration issues with 3rd party packages
# https://docs.djangoproject.com/en/5.1/releases/5.0/#automatic-primary-key-fields
# DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Django REST Framework settings
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
        # Add other authentication classes if needed
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        # 'rest_framework.permissions.IsAuthenticatedOrReadOnly',
    ],
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle'
    ],
    'DEFAULT_THROTTLE_RATES': {
        'email': '50/day', # Specific rate for contact form email endpoint
        'anon': '1000/hour', # Default rate for anonymous users (increased)
        'user': '1000/hour' # Default rate for authenticated users (increased)
    }
}


# Add feature flag settings
FLAGS = {
    # Add feature flag so that ropon_id can be used in the API to get ObservingNetworkPage(ON) details
    'ROPON.DATA.ENABLE_ON_API_ROPONID_DETAILS': [
        {"condition": "boolean",
         "value": env.bool('ROPON.DATA.ENABLE_ON_API_ROPONID_DETAILS', False),
        }
    ],
    # Add feature flag to remove side panel options for Moderators and Editors
    'ROPON.REMOVE_SIDE_PANEL_OPTIONS': [
        {"condition": "boolean",
         "value": env.bool('ROPON.REMOVE_SIDE_PANEL_OPTIONS', False),
        }
    ],
    # Add feature flag for aging observing networks report
    'ROPON.REPORTS.AGING_OBSERVING_NETWORKS': [
        {"condition": "boolean",
         "value": env.bool('ROPON.REPORTS.AGING_OBSERVING_NETWORKS', False),
        }
    ],
    # Add feature flag to remove preview options for pages as it is Headless CMS
    'ROPON.REMOVE_PREVIEW_OPTIONS': [
        {"condition": "boolean",
         "value": env.bool('ROPON.REMOVE_PREVIEW_OPTIONS', False),
        }
    ],
    # Add feature flag to activate WAGTAIL_GUIDE
    'ROPON.ENABLE_WAGTAIL_GUIDE': [
        {"condition": "boolean",
         "value": env.bool('ROPON.ENABLE_WAGTAIL_GUIDE', False),
        }
    ],
    # Add feature flag to enable moderators to manage users
    'ROPON.AUTH.MODERATOR_USER_MANAGEMENT': [
        {"condition": "boolean",
         "value": env.bool('ROPON.AUTH.MODERATOR_USER_MANAGEMENT', False),
        }
    ]
}


# Wagtail guide package settings
WAGTAIL_GUIDE_SETTINGS = {
    # Whether to add the guide to the help menu
    "ADD_WAGTAIL_GUIDE_TO_HELP_MENU": env.bool("WAGTAIL_GUIDE_ADD_TO_HELP_MENU", False),
    # Custom label for the guide in the menu
    "WAGTAIL_GUIDE_MENU_LABEL": env.str("WAGTAIL_GUIDE_MENU_LABEL", "Editor's Guide"),
    # Whether to hide the core editor guide
    "HIDE_WAGTAIL_CORE_EDITOR_GUIDE": env.bool("WAGTAIL_GUIDE_HIDE_CORE_EDITOR", True),
}
