# Generated by Django 5.1.5 on 2025-01-29 23:10

import ropon_auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ropon_auth", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="roponuser",
            managers=[
                ("objects", ropon_auth.models.RoponUserManager()),
            ],
        ),
    ]
